### ISSUE TITLE
getActivePaymentMethodCodes Exception on Checkout page - Magento 2.4.2

### ISSUE THREAD

**Issue by bernieu2** [AddressFinder/addressfinder-magento#75]
After upgrading Magento 2.4 to 2.4.2 the following exception occurs on /checkout/ page load which results in a blank page: 

```
<script>
--
  | require(['magento_plugin', 'addressfinder', 'domReady!'], function (MagentoPlugin, AddressFinder) {
  | var widgetConfig = {"key":"*******************","options":{"address_params":{"au_paf":"1"}},"debug":true,"default_country":"au"};
  | var formsConfig = An error has happened during application run. See exception log for details.

```
Output in system.log: 
[2021-03-06 04:03:36] main.CRITICAL: Error: Call to a member function getPayment() on null in /home/realbasi/madge/vendor/stripe/module-payments/Model/Method/Express.php:29

> Stack trace:
#0 /home/realbasi/madge/vendor/magento/module-payment/Helper/Data.php(146): StripeIntegration\Payments\Model\Method\Express->isAvailable(NULL)
**#1 /home/realbasi/madge/vendor/addressfinder/module-magento2/Observer/FormConfig/Frontend/AddCheckoutBillingAddress.php(132): Magento\Payment\Helper\Data->getStoreMethods()**
**#2 /home/realbasi/madge/vendor/addressfinder/module-magento2/Observer/FormConfig/Frontend/AddCheckoutBillingAddress.php(41): AddressFinder\AddressFinder\Observer\FormConfig\Frontend\AddCheckoutBillingAddress->getActivePaymentMethodCodes()**
#3 /home/realbasi/madge/vendor/addressfinder/module-magento2/Observer/FormConfig/Base.php(52): AddressFinder\AddressFinder\Observer\FormConfig\Frontend\AddCheckoutBillingAddress->addForm(Object(Magento\Framework\Data\Collection\Interceptor))
#4 /home/realbasi/madge/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): AddressFinder\AddressFinder\Observer\FormConfig\Base->execute(Object(Magento\Framework\Event\Observer))
#5 /home/realbasi/madge/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(AddressFinder\AddressFinder\Observer\FormConfig\Frontend\AddCheckoutBillingAddress), Object(Magento\Framework\Event\Observer))
#6 /home/realbasi/madge/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#7 /home/realbasi/madge/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('addressfinder_f...', Array)
#8 /home/realbasi/madge/vendor/addressfinder/module-magento2/Model/FormConfigProvider.php(75): Magento\Framework\Event\Manager\Proxy->dispatch('addressfinder_f...', Array)
#9 /home/realbasi/madge/vendor/addressfinder/module-magento2/Block/Plugin.php(59): AddressFinder\AddressFinder\Model\FormConfigProvider->get('addressfinder_f...')
#10 /home/realbasi/madge/var/view_preprocessed/pub/static/vendor/addressfinder/module-magento2/view/frontend/templates/plugin.phtml(4): AddressFinder\AddressFinder\Block\Plugin->getFormsConfig()
#11 /home/realbasi/madge/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/realbasi/...')

I note you have this on your todo list already so perhaps you're already aware of this issue - but seems you need to update the getActivePaymentMethodCodes() method in AddCheckoutBillingAddress observer to use the Api method instead. After testing with below code the exception no longer occurs and addressfinder works as expected. 

```
    private function getActivePaymentMethodCodes(): array
    {
        $codes = [];

        // @todo Visit working around deprecated code

        $paymentApi = \Magento\Framework\App\ObjectManager::getInstance()
                ->get(\Magento\Payment\Api\PaymentMethodListInterface::class);
        $storeId = \Magento\Framework\App\ObjectManager::getInstance()
                ->get(\Magento\Store\Model\StoreManagerInterface::class)->getStore()->getId();

         foreach ($paymentApi->getActiveList($storeId) as $method) {

            try {
                $codes[] = $method->getCode();
            } catch (LocalizedException $e) {
            }
        }

        return $codes;
    }
```

Result: 

```
<script>
--
  | require(['magento_plugin', 'addressfinder', 'domReady!'], function (MagentoPlugin, AddressFinder) {
  | var widgetConfig = {"key":"********************","options":{"address_params":{"au_paf":"1"}},"debug":true,"default_country":"au"};
  | var formsConfig = [{"id":"frontend.checkout.billing.address.payflow_express","label":"Checkout Billing Address (payflow_express)","layoutSelectors":["li#payment","div[name=\"billingAddresspayflow_express.street.0\"]"],"countryIdentifier":"div[name=\"billingAddresspayflow_express.country_id\"] select[name=country_id]","searchIdentifier":"div[name=\"billingAddresspayflow_express.street.0\"] input[name=\"street[0]\"]","nz":{"countryValue":"NZ","elements":{"address1":"div[name=\"billingAddresspayflow_express.street.0\"] input[name=\"street[0]\"]","address2":"div[name=\"billingAddresspayflow_express.street.1\"] input[name=\"street[1]\"]","suburb":"div[name=\"billingAddresspayflow_express.street.2\"] input[name=\"street[2]\"]","city":"div[name=\"billingAddresspayflow_express.city\"] input[name=city]","region":"div[name=\"billingAddresspayflow_express.region\"] input[name=region]","postcode":"div[name=\"billingAddresspayflow_express.postcode\"] input[name=postcode]"},"regionMappings":null},"au":{"countryValue":"AU","elements":{"address1":"div[name=\"billingAddresspayflow_express.street.0\"] input[name=\"street[0]\"]","address2":"div[name=\"billingAddresspayflow_express.street.1\"] input[name=\"street[1]\"]","suburb":"div[name=\"billingAddresspayflow_express.city\"] input[name=city]","state":"div[name=\"billingAddresspayflow_express.region_id\"] select[name=region_id]","postcode":"div[name=\"billingAddresspayflow_express.postcode\"] input[name=postcode]"},"stateMappings":{"ACT":569,"NSW":570,"NT":576,"QLD":572,"SA":573,"TAS":574,"VIC":571,"WA":575}}},{"id":"frontend.checkout.billing.address.paypal_express_bml","label":"Checkout Billing Address (paypal_express_bml)","layoutSelectors":["li#payment","div[name=\"billingAddresspaypal_express_bml.street.0\"]"],"countryIdentifier":"div[name=\"billingAddresspaypal_express_bml.country_id\"] select[name=country_id]","searchIdentifier":"div[name=\"billingAddresspaypal_express_bml.street.0\"] input[name=\"street[0]\"]","nz":{"countryValue":"NZ","elements":{"address1":"div[name=\"billingAddresspaypal_express_bml.street.0\"] input[name=\"street[0]\"]","address2":"div[name=\"billingAddresspaypal_express_bml.street.1\"] input[name=\"street[1]\"]","suburb":"div[name=\"billingAddresspaypal_express_bml.street.2\"] input[name=\"street[2]\"]","city":"div[name=\"billingAddresspaypal_express_bml.city\"] input[name=city]","region":"div[name=\"billingAddresspaypal_express_bml.region\"] input[name=region]","postcode":"div[name=\"billingAddresspaypal_express_bml.postcode\"] input[name=postcode]"},"regionMappings":null},"au":{"countryValue":"AU","elements":{"address1":"div[name=\"billingAddresspaypal_express_bml.street.0\"] input[name=\"street[0]\"]","address2":"div[name=\"billingAddresspaypal_express_bml.street.1\"] input[name=\"street[1]\"]","suburb":"div[name=\"billingAddresspaypal_express_bml.city\"] input[name=city]","state":"div[name=\"billingAddresspaypal_express_bml.region_id\"] select[name=region_id]","postcode":"div[name=\"billingAddresspaypal_express_bml.postcode\"] input[name=postcode]"},"stateMappings":{"ACT":569,"NSW":570,"NT":576,"QLD":572,"SA":573,"TAS":574,"VIC":571,"WA":575}}},{"id":"frontend.checkout.billing.address.payflow_express_bml","label":"Checkout Billing Address (payflow_express_bml)","layoutSelectors":["li#payment","div[name=\"billingAddresspayflow_express_bml.street.0\"]"],"countryIdentifier":"div[name=\"billingAddresspayflow_express_bml.country_id\"] select[name=country_id]","searchIdentifier":"div[name=\"billingAddresspayflow_express_bml.street.0\"] input[name=\"street[0]\"]","nz":{"countryValue":"NZ","elements":{"address1":"div[name=\"billingAddresspayflow_express_bml.street.0\"] input[name=\"street[0]\"]","address2":"div[name=\"billingAddresspayflow_express_bml.street.1\"] input[name=\"street[1]\"]","suburb":"div[name=\"billingAddresspayflow_express_bml.street.2\"] input[name=\"street[2]\"]","city":"div[name=\"billingAddresspayflow_express_bml.city\"] input[name=city]","region":"div[name=\"billingAddresspayflow_express_bml.region\"] input[name=region]","postcode":"div[name=\"billingAddresspayflow_express_bml.postcode\"] input[name=postcode]"},"regionMappings":null},"au":{"countryValue":"AU","elements":{"address1":"div[name=\"billingAddresspayflow_express_bml.street.0\"] input[name=\"street[0]\"]","address2":"div[name=\"billingAddresspayflow_express_bml.street.1\"] input[name=\"street[1]\"]","suburb":"div[name=\"billingAddresspayflow_express_bml.city\"] input[name=city]","state":"div[name=\"billingAddresspayflow_express_bml.region_id\"] select[name=region_id]","postcode":"div[name=\"billingAddresspayflow_express_bml.postcode\"] input[name=postcode]"},"stateMappings":{"ACT":569,"NSW":570,"NT":576,"QLD":572,"SA":573,"TAS":574,"VIC":571,"WA":575}}},{"id":"frontend.checkout.billing.address.free","label":"Checkout Billing Address (free)","layoutSelectors":
... truncated... 
```

**Comment by erikfercak** [comment]
Thank you for your report, we'll investigate.
